version: '3'

services:
  mysql:
    image: mysql:8.2.0-oracle
    container_name: spring_batch
    environment:
      MYSQL_DATABASE: "springBatchTest"
      MYSQL_ROOT_PASSWORD: "rh3dlekx123@"
      TZ: "Asia/Seoul"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
